# Generated by Django 5.0.3 on 2024-03-06 06:10

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
    ]
