# Generated by Django 5.0.3 on 2024-03-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_options_remove_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(max_length=10),
        ),
    ]
